import type { Product } from "@/types";

export const products: Product[] = [
  {
    id: "path-aero-01",
    slug: "path-aero-flow",
    name: "PATH Aero Flow",
    brand: "PATH",
    description:
      "A sculpted lifestyle runner with lightweight cushioning and a precise everyday fit.",
    price: 189,
    compareAtPrice: 219,
    category: "running",
    gender: "unisex",
    colors: ["white", "silver"],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
    images: [
      {
        id: "path-aero-hero",
        src: "/products/path-aero-flow-white.jpg",
        alt: "PATH Aero Flow sneaker in white and silver",
        color: "white",
      },
    ],
    variants: [
      {
        id: "path-aero-white",
        color: "white",
        colorHex: "#f7f7f2",
        sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
      },
      {
        id: "path-aero-silver",
        color: "silver",
        colorHex: "#c8ccd0",
        sizes: ["US 8", "US 9", "US 10", "US 11"],
      },
    ],
    rating: 4.8,
    reviewCount: 128,
    isNew: true,
    isTrending: true,
    isFeatured: true,
    materials: ["Engineered mesh", "Cloud foam midsole", "Rubber outsole"],
    createdAt: "2026-05-01T00:00:00.000Z",
    updatedAt: "2026-05-20T00:00:00.000Z",
  },
  {
    id: "path-court-02",
    slug: "path-court-zero",
    name: "PATH Court Zero",
    brand: "PATH",
    description:
      "A low-profile court sneaker built with premium leather, quiet branding, and all-day support.",
    price: 165,
    compareAtPrice: null,
    category: "lifestyle",
    gender: "men",
    colors: ["black", "white"],
    sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
    images: [
      {
        id: "path-court-hero",
        src: "/products/path-court-zero-black.jpg",
        alt: "PATH Court Zero sneaker in black leather",
        color: "black",
      },
    ],
    variants: [
      {
        id: "path-court-black",
        color: "black",
        colorHex: "#111111",
        sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
      },
      {
        id: "path-court-white",
        color: "white",
        colorHex: "#ffffff",
        sizes: ["US 8", "US 9", "US 10"],
      },
    ],
    rating: 4.6,
    reviewCount: 86,
    isNew: false,
    isTrending: true,
    isFeatured: true,
    materials: ["Full-grain leather", "Cushioned collar", "Rubber cupsole"],
    createdAt: "2026-04-08T00:00:00.000Z",
    updatedAt: "2026-05-12T00:00:00.000Z",
  },
  {
    id: "path-pulse-03",
    slug: "path-pulse-knit",
    name: "PATH Pulse Knit",
    brand: "PATH",
    description:
      "A breathable knit trainer with responsive stability for gym sessions and city movement.",
    price: 148,
    compareAtPrice: 178,
    category: "training",
    gender: "women",
    colors: ["cream", "green"],
    sizes: ["US 5", "US 6", "US 7", "US 8", "US 9"],
    images: [
      {
        id: "path-pulse-hero",
        src: "/products/path-pulse-knit-cream.jpg",
        alt: "PATH Pulse Knit sneaker in cream",
        color: "cream",
      },
    ],
    variants: [
      {
        id: "path-pulse-cream",
        color: "cream",
        colorHex: "#efe7d2",
        sizes: ["US 5", "US 6", "US 7", "US 8", "US 9"],
      },
      {
        id: "path-pulse-green",
        color: "green",
        colorHex: "#6f8065",
        sizes: ["US 6", "US 7", "US 8"],
      },
    ],
    rating: 4.7,
    reviewCount: 64,
    isNew: true,
    isTrending: false,
    isFeatured: false,
    materials: ["Knit upper", "Stability plate", "Textured rubber outsole"],
    createdAt: "2026-05-14T00:00:00.000Z",
    updatedAt: "2026-05-24T00:00:00.000Z",
  },
  {
    id: "path-vault-04",
    slug: "path-vault-high",
    name: "PATH Vault High",
    brand: "PATH",
    description:
      "A premium high-top silhouette with layered panels, padded ankle support, and a bold stance.",
    price: 210,
    compareAtPrice: null,
    category: "basketball",
    gender: "unisex",
    colors: ["red", "black"],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    images: [
      {
        id: "path-vault-hero",
        src: "/products/path-vault-high-red.jpg",
        alt: "PATH Vault High sneaker in red and black",
        color: "red",
      },
    ],
    variants: [
      {
        id: "path-vault-red",
        color: "red",
        colorHex: "#b91c1c",
        sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
      },
      {
        id: "path-vault-black",
        color: "black",
        colorHex: "#171717",
        sizes: ["US 8", "US 9", "US 10", "US 11"],
      },
    ],
    rating: 4.9,
    reviewCount: 141,
    isNew: false,
    isTrending: true,
    isFeatured: false,
    materials: ["Nubuck overlays", "Foam midsole", "Herringbone traction"],
    createdAt: "2026-03-18T00:00:00.000Z",
    updatedAt: "2026-05-18T00:00:00.000Z",
  },
];
